--------------------------------------------------------
-- Archivo creado  - miércoles-octubre-03-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BODEGA
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."BODEGA" 
   (	"ID" VARCHAR2(30 BYTE), 
	"ID_SUCURSAL" VARCHAR2(30 BYTE), 
	"PESO" NUMBER, 
	"PESO_ACTUAL" NUMBER, 
	"VOLUMEN" NUMBER, 
	"VOLUMEN_ACTUAL" NUMBER, 
	"TIPO_PRODUCTO" VARCHAR2(20 BYTE), 
	"UNIDAD_PESO" NUMBER, 
	"UNIDAD_VOLUMEN" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table COMPRA
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."COMPRA" 
   (	"ID" VARCHAR2(30 BYTE), 
	"PRECIO" NUMBER, 
	"ID_CLIENTE" VARCHAR2(30 BYTE), 
	"ID_SUCURSAL" VARCHAR2(30 BYTE), 
	"ID_PRODUCTO" VARCHAR2(30 BYTE), 
	"CANTIDAD" NUMBER, 
	"PROMOCION" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table COMPRA_PROMOCION
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."COMPRA_PROMOCION" 
   (	"ID_COMPRA" VARCHAR2(30 BYTE), 
	"ID_PROMOCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table EMPRESAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."EMPRESAS" 
   (	"NIT" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table ESTANTE
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."ESTANTE" 
   (	"ID" VARCHAR2(30 BYTE), 
	"ID_SUCURSAL" VARCHAR2(30 BYTE), 
	"TIPO_PRODUCTO" VARCHAR2(20 BYTE), 
	"VOLUMEN" NUMBER, 
	"VOLUMEN_ACTUAL" NUMBER, 
	"PESO" NUMBER, 
	"PESO_ACTUAL" NUMBER, 
	"UNIDAD_VOLUMEN" NUMBER, 
	"UNIDAD_PESO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table LLEGADA_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."LLEGADA_PRODUCTO" 
   (	"ID_PRODUCTO" VARCHAR2(30 BYTE), 
	"ID_ORDEN" VARCHAR2(30 BYTE), 
	"VOLUMEN" NUMBER, 
	"UNIDAD_MEDIDA" VARCHAR2(20 BYTE), 
	"CANTIDAD_RECIBIDA" NUMBER, 
	"CALIDAD_RECIBIDA" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table ORDEN_PEDIDO
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."ORDEN_PEDIDO" 
   (	"ID" VARCHAR2(30 BYTE), 
	"FECHAESPERDA" DATE, 
	"ESTADO" VARCHAR2(20 BYTE), 
	"ID_PROVEDOR" VARCHAR2(30 BYTE), 
	"ID_SUCURSAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PERSONAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."PERSONAS" 
   (	"CEDULA" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."PRODUCTO" 
   (	"CODIGODEBARRAS" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(25 BYTE), 
	"MARCA" VARCHAR2(25 BYTE), 
	"PRESENTACION" VARCHAR2(20 BYTE), 
	"PRECIOPORUNIDADDEMEDIDA" NUMBER, 
	"UNIDADDEMEDIDA" VARCHAR2(20 BYTE), 
	"CANTIDADENLAPRESENTACION" NUMBER, 
	"VOLUMEN" NUMBER, 
	"PESO" NUMBER, 
	"CATEGORIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO_PROVEDOR
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."PRODUCTO_PROVEDOR" 
   (	"ID_PRODUCTO" VARCHAR2(30 BYTE), 
	"ID_PROVEDOR" VARCHAR2(30 BYTE), 
	"PRECIO" NUMBER, 
	"INDICE_CALIDAD" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PROMOCION
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."PROMOCION" 
   (	"ID" VARCHAR2(30 BYTE), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE, 
	"ID_PRODUCTO" VARCHAR2(30 BYTE), 
	"ID_SUCURSAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PROVEDOR
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."PROVEDOR" 
   (	"NIT" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table SUCURSAL
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."SUCURSAL" 
   (	"ID" VARCHAR2(30 BYTE), 
	"CIUDAD" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table SUCURSAL_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304B191820"."SUCURSAL_PRODUCTO" 
   (	"ID_SUCURSAL" VARCHAR2(30 BYTE), 
	"ID_PRODUCTO" VARCHAR2(30 BYTE), 
	"PRECIO" NUMBER, 
	"NIVEL_REORDEN" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
REM INSERTING into ISIS2304B191820.BODEGA
SET DEFINE OFF;
REM INSERTING into ISIS2304B191820.COMPRA
SET DEFINE OFF;
REM INSERTING into ISIS2304B191820.COMPRA_PROMOCION
SET DEFINE OFF;
Insert into ISIS2304B191820.COMPRA_PROMOCION (ID_COMPRA,ID_PROMOCION) values ('2141','513');
Insert into ISIS2304B191820.COMPRA_PROMOCION (ID_COMPRA,ID_PROMOCION) values ('311','214');
Insert into ISIS2304B191820.COMPRA_PROMOCION (ID_COMPRA,ID_PROMOCION) values ('3413','214');
REM INSERTING into ISIS2304B191820.EMPRESAS
SET DEFINE OFF;
REM INSERTING into ISIS2304B191820.ESTANTE
SET DEFINE OFF;
REM INSERTING into ISIS2304B191820.LLEGADA_PRODUCTO
SET DEFINE OFF;
REM INSERTING into ISIS2304B191820.ORDEN_PEDIDO
SET DEFINE OFF;
REM INSERTING into ISIS2304B191820.PERSONAS
SET DEFINE OFF;
REM INSERTING into ISIS2304B191820.PRODUCTO
SET DEFINE OFF;
Insert into ISIS2304B191820.PRODUCTO (CODIGODEBARRAS,NOMBRE,MARCA,PRESENTACION,PRECIOPORUNIDADDEMEDIDA,UNIDADDEMEDIDA,CANTIDADENLAPRESENTACION,VOLUMEN,PESO,CATEGORIA) values ('11111','Manzana','La Naturaleza','Por Unidad','500','Lb','1','300','100','Frutas');
Insert into ISIS2304B191820.PRODUCTO (CODIGODEBARRAS,NOMBRE,MARCA,PRESENTACION,PRECIOPORUNIDADDEMEDIDA,UNIDADDEMEDIDA,CANTIDADENLAPRESENTACION,VOLUMEN,PESO,CATEGORIA) values ('11112','Pera','La Naturaleza','Por Unidad','600','Lb','1','400','110','Frutas');
Insert into ISIS2304B191820.PRODUCTO (CODIGODEBARRAS,NOMBRE,MARCA,PRESENTACION,PRECIOPORUNIDADDEMEDIDA,UNIDADDEMEDIDA,CANTIDADENLAPRESENTACION,VOLUMEN,PESO,CATEGORIA) values ('11113','Banano','La Naturaleza','Por Unidad','500','Lb','1','250','60','Frutas');
REM INSERTING into ISIS2304B191820.PRODUCTO_PROVEDOR
SET DEFINE OFF;
REM INSERTING into ISIS2304B191820.PROMOCION
SET DEFINE OFF;
Insert into ISIS2304B191820.PROMOCION (ID,FECHA_INICIO,FECHA_FIN,ID_PRODUCTO,ID_SUCURSAL) values ('12',to_date('03/10/18','DD/MM/RR'),to_date('10/10/18','DD/MM/RR'),'642','245');
Insert into ISIS2304B191820.PROMOCION (ID,FECHA_INICIO,FECHA_FIN,ID_PRODUCTO,ID_SUCURSAL) values ('24',to_date('03/02/18','DD/MM/RR'),to_date('01/01/19','DD/MM/RR'),'313','414');
Insert into ISIS2304B191820.PROMOCION (ID,FECHA_INICIO,FECHA_FIN,ID_PRODUCTO,ID_SUCURSAL) values ('32',to_date('04/09/18','DD/MM/RR'),to_date('04/10/18','DD/MM/RR'),'3134','341');
REM INSERTING into ISIS2304B191820.PROVEDOR
SET DEFINE OFF;
REM INSERTING into ISIS2304B191820.SUCURSAL
SET DEFINE OFF;
Insert into ISIS2304B191820.SUCURSAL (ID,CIUDAD,DIRECCION) values ('2183','Bogotá','calle 106');
Insert into ISIS2304B191820.SUCURSAL (ID,CIUDAD,DIRECCION) values ('3131','Cali','calle 45');
REM INSERTING into ISIS2304B191820.SUCURSAL_PRODUCTO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BODEGA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."BODEGA_PK" ON "ISIS2304B191820"."BODEGA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index COMPRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."COMPRA_PK" ON "ISIS2304B191820"."COMPRA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index COMPRA_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."COMPRA_UK1" ON "ISIS2304B191820"."COMPRA" ("ID_CLIENTE", "ID_SUCURSAL", "ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index COMPRA_PROMOCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."COMPRA_PROMOCION_PK" ON "ISIS2304B191820"."COMPRA_PROMOCION" ("ID_COMPRA", "ID_PROMOCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index EMPRESAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."EMPRESAS_PK" ON "ISIS2304B191820"."EMPRESAS" ("NIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index ESTANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."ESTANTE_PK" ON "ISIS2304B191820"."ESTANTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index LLEGADA_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."LLEGADA_PRODUCTO_PK" ON "ISIS2304B191820"."LLEGADA_PRODUCTO" ("ID_PRODUCTO", "ID_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index ORDEN_PEDIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."ORDEN_PEDIDO_PK" ON "ISIS2304B191820"."ORDEN_PEDIDO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PERSONAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."PERSONAS_PK" ON "ISIS2304B191820"."PERSONAS" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PERSONAS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."PERSONAS_UK1" ON "ISIS2304B191820"."PERSONAS" ("NOMBRE", "CORREO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."PRODUCTO_PK" ON "ISIS2304B191820"."PRODUCTO" ("CODIGODEBARRAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."PRODUCTO_UK1" ON "ISIS2304B191820"."PRODUCTO" ("NOMBRE", "CODIGODEBARRAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."PRODUCTO_UK2" ON "ISIS2304B191820"."PRODUCTO" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PROVEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."PRODUCTO_PROVEDOR_PK" ON "ISIS2304B191820"."PRODUCTO_PROVEDOR" ("ID_PRODUCTO", "ID_PROVEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PROMOCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."PROMOCION_PK" ON "ISIS2304B191820"."PROMOCION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PROVEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."PROVEDOR_PK" ON "ISIS2304B191820"."PROVEDOR" ("NIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PROVEDOR_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."PROVEDOR_UK1" ON "ISIS2304B191820"."PROVEDOR" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."CLIENTE_PK" ON "ISIS2304B191820"."SUCURSAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index SUCURSAL_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."SUCURSAL_UK1" ON "ISIS2304B191820"."SUCURSAL" ("ID", "DIRECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index SUCURSAL_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."SUCURSAL_UK2" ON "ISIS2304B191820"."SUCURSAL" ("DIRECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index SUCURSALPRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304B191820"."SUCURSALPRODUCTO_PK" ON "ISIS2304B191820"."SUCURSAL_PRODUCTO" ("ID_SUCURSAL", "ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  Constraints for Table BODEGA
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."BODEGA" MODIFY ("UNIDAD_VOLUMEN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."BODEGA" MODIFY ("UNIDAD_PESO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."BODEGA" MODIFY ("TIPO_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."BODEGA" MODIFY ("VOLUMEN_ACTUAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."BODEGA" MODIFY ("VOLUMEN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."BODEGA" MODIFY ("PESO_ACTUAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."BODEGA" MODIFY ("PESO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."BODEGA" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."BODEGA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."BODEGA" ADD CONSTRAINT "BODEGA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."BODEGA" ADD CONSTRAINT "BODEGA_CHK1" CHECK (Volumen >0 and peso >0 and peso_actual > 0 and volumen_actual > 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPRA
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."COMPRA" MODIFY ("PROMOCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."COMPRA" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."COMPRA" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."COMPRA" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."COMPRA" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."COMPRA" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."COMPRA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."COMPRA" ADD CONSTRAINT "COMPRA_UK1" UNIQUE ("ID_CLIENTE", "ID_SUCURSAL", "ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."COMPRA" ADD CONSTRAINT "COMPRA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."COMPRA" ADD CONSTRAINT "COMPRA_CHK1" CHECK (precio > 0 and cantidad >0) ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPRA_PROMOCION
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."COMPRA_PROMOCION" MODIFY ("ID_PROMOCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."COMPRA_PROMOCION" MODIFY ("ID_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."COMPRA_PROMOCION" ADD CONSTRAINT "COMPRA_PROMOCION_PK" PRIMARY KEY ("ID_COMPRA", "ID_PROMOCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPRESAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."EMPRESAS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."EMPRESAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."EMPRESAS" MODIFY ("NIT" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."EMPRESAS" ADD CONSTRAINT "EMPRESAS_PK" PRIMARY KEY ("NIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTANTE
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."ESTANTE" MODIFY ("UNIDAD_PESO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ESTANTE" MODIFY ("UNIDAD_VOLUMEN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ESTANTE" MODIFY ("PESO_ACTUAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ESTANTE" MODIFY ("PESO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ESTANTE" MODIFY ("VOLUMEN_ACTUAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ESTANTE" MODIFY ("VOLUMEN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ESTANTE" MODIFY ("TIPO_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ESTANTE" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ESTANTE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ESTANTE" ADD CONSTRAINT "ESTANTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."ESTANTE" ADD CONSTRAINT "ESTANTE_CHK1" CHECK (peso > 0 and peso_actual > 0 and volumen > 0 and volumen_actual > 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table LLEGADA_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."LLEGADA_PRODUCTO" MODIFY ("CALIDAD_RECIBIDA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."LLEGADA_PRODUCTO" MODIFY ("CANTIDAD_RECIBIDA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."LLEGADA_PRODUCTO" MODIFY ("UNIDAD_MEDIDA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."LLEGADA_PRODUCTO" MODIFY ("VOLUMEN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."LLEGADA_PRODUCTO" MODIFY ("ID_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."LLEGADA_PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."LLEGADA_PRODUCTO" ADD CONSTRAINT "LLEGADA_PRODUCTO_PK" PRIMARY KEY ("ID_PRODUCTO", "ID_ORDEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."LLEGADA_PRODUCTO" ADD CONSTRAINT "LLEGADA_PRODUCTO_CHK1" CHECK (Volumen > 0 and calidad_recibida > 0 and cantidad_recibida > 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDEN_PEDIDO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."ORDEN_PEDIDO" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ORDEN_PEDIDO" MODIFY ("ID_PROVEDOR" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ORDEN_PEDIDO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ORDEN_PEDIDO" MODIFY ("FECHAESPERDA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ORDEN_PEDIDO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."ORDEN_PEDIDO" ADD CONSTRAINT "ORDEN_PEDIDO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."PERSONAS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PERSONAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PERSONAS" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PERSONAS" ADD CONSTRAINT "PERSONAS_UK1" UNIQUE ("NOMBRE", "CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."PERSONAS" ADD CONSTRAINT "PERSONAS_PK" PRIMARY KEY ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."PRODUCTO" MODIFY ("CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" MODIFY ("PESO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" MODIFY ("VOLUMEN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" MODIFY ("CANTIDADENLAPRESENTACION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" MODIFY ("UNIDADDEMEDIDA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" MODIFY ("PRECIOPORUNIDADDEMEDIDA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" MODIFY ("PRESENTACION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" MODIFY ("MARCA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" MODIFY ("CODIGODEBARRAS" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_UK2" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_UK1" UNIQUE ("NOMBRE", "CODIGODEBARRAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("CODIGODEBARRAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_CHK1" CHECK (Peso > 0 and volumen > 0 and precioporunidaddemedida >0) ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO_PROVEDOR
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."PRODUCTO_PROVEDOR" MODIFY ("INDICE_CALIDAD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO_PROVEDOR" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO_PROVEDOR" MODIFY ("ID_PROVEDOR" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO_PROVEDOR" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PRODUCTO_PROVEDOR" ADD CONSTRAINT "PRODUCTO_PROVEDOR_PK" PRIMARY KEY ("ID_PRODUCTO", "ID_PROVEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."PRODUCTO_PROVEDOR" ADD CONSTRAINT "PRODUCTO_PROVEDOR_CHK1" CHECK (precio > 0 and indice_calidad >0) ENABLE;
--------------------------------------------------------
--  Constraints for Table PROMOCION
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."PROMOCION" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PROMOCION" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PROMOCION" MODIFY ("FECHA_FIN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PROMOCION" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PROMOCION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PROMOCION" ADD CONSTRAINT "PROMOCION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVEDOR
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."PROVEDOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PROVEDOR" MODIFY ("NIT" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."PROVEDOR" ADD CONSTRAINT "PROVEDOR_UK1" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."PROVEDOR" ADD CONSTRAINT "PROVEDOR_PK" PRIMARY KEY ("NIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUCURSAL
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."SUCURSAL" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."SUCURSAL" MODIFY ("CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."SUCURSAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."SUCURSAL" ADD CONSTRAINT "SUCURSAL_UK2" UNIQUE ("DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."SUCURSAL" ADD CONSTRAINT "SUCURSAL_UK1" UNIQUE ("ID", "DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304B191820"."SUCURSAL" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUCURSAL_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304B191820"."SUCURSAL_PRODUCTO" MODIFY ("NIVEL_REORDEN" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."SUCURSAL_PRODUCTO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."SUCURSAL_PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."SUCURSAL_PRODUCTO" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304B191820"."SUCURSAL_PRODUCTO" ADD CONSTRAINT "SUCURSAL_PRODUCTO_CHK1" CHECK (precio > 0 and nivel_reorden > 0) ENABLE;
  ALTER TABLE "ISIS2304B191820"."SUCURSAL_PRODUCTO" ADD CONSTRAINT "SUCURSALPRODUCTO_PK" PRIMARY KEY ("ID_SUCURSAL", "ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
